### ISSUE TITLE
MIT Licence retrospective?

### ISSUE THREAD

**Issue by adrianfalleiro** [IonicaBizau/youtube-api#47]
Are versions 1.0.0 to 1.3.0 still licensed under KINDLY license?

Also, just curiously, what made you change your mind to relicense this as MIT?

**Comment by IonicaBizau** [comment]
> Are versions 1.0.0 to 1.3.0 still licensed under KINDLY license?

Yes, but you can safely upgrade to `1.4.0` because there were not made any (big) changes in the code.

> Also, just curiously, what made you change your mind to relicense this as MIT?

The questions would be what I decided to relicense to KINDLY. :smirk: It was an interesting experiment. Honestly, I wanted to get some money donations because of my GitHub activity (it doesn't matter how much, just $1 is really welcome). But that didn't make a big difference. In the mean time, I had another opportunity: I started teaching people how to Node.js/Git/JavaScript and I found it really difficult to use my stuff in their closed-source apps.

In fact, the KINDLY license complicated the things a little bit. I relicensed everything (back) to MIT allowing anybody to use my stuff in their apps and proudly call it *open-source* again. :sparkles:  

Of course, [your support](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RVXDDLKKLQRJW) is still welcome! :sparkling_heart:
